config/routes.rb
Notility::Application.routes.draw do
  get "static_pages/home"

  get "static_pages/help"

  resources :notes

  resources :courses

  resources :users

  match 'get_note/:id' => 'notes#get_note'

   root :to => 'static_pages#home'

end

app/models/course.rb
# == Schema Information
#
# Table name: courses
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Course < ActiveRecord::Base
  attr_accessible :name
  has_many :notes, dependent: :destroy
end

app/models/note.rb
# == Schema Information
#
# Table name: notes
#
#  id         :integer          not null, primary key
#  content    :string(255)
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  tag        :string(255)
#  course_id  :integer
#

class Note < ActiveRecord::Base
  attr_accessible :content, :course_id, :tag

  belongs_to :course

  validates :course_id, presence: true

  default_scope order: 'notes.created_at DESC'

  def self.search(search)
    if search
      where('tag LIKE ?', "%#{search}%")
    else
      scoped
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @courses }
    end
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    @course = Course.find(params[:id])

=begin
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @course }
    end
=end
    @notes = @course.notes
  end

  # GET /courses/new
  # GET /courses/new.json
  def new
    @course = Course.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @course }
    end
  end

  # GET /courses/1/edit
  def edit
    @course = Course.find(params[:id])
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(params[:course])

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render json: @course, status: :created, location: @course }
      else
        format.html { render action: "new" }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /courses/1
  # PUT /courses/1.json
  def update
    @course = Course.find(params[:id])

    respond_to do |format|
      if @course.update_attributes(params[:course])
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course = Course.find(params[:id])
    @course.destroy

    respond_to do |format|
      format.html { redirect_to courses_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  # GET /notes
  # GET /notes.json

  respond_to :html, :json, :xml

  skip_before_filter  :verify_authenticity_token

  def index
    #@notes = Note.all
    @notes = Note.search(params[:search])

=begin
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @notes }
      format.xml { render xml: @notes }
    end
=end

  end

  def get_note
    @notes = Note.search(params[:id])
    respond_to do |format|
      format.html # index.html.erb
      format.xml { render xml: @notes }
    end
  end


  # GET /notes/1
  # GET /notes/1.json
  def show
    @note = Note.find(params[:id])
    respond_with @note
  end

  # GET /notes/new
  # GET /notes/new.json
  def new
    @note = Note.new
    respond_with @note
  end

  # GET /notes/1/edit
  def edit
    @note = Note.find(params[:id])
    respond_with @note
  end

  # POST /notes
  # POST /notes.json
  # POST /notes.xml

  def create
    @note = Note.new(params[:note])

=begin
    $ curl -H 'Content-Type: application/xml'   -X POST -d '<?xml version="1.0" encoding="UTF-8"?>
<note>
  <content>note from api 2</content>
  <course_id>2</course_id>
  <tag>api</tag>
</note> http://notility.herokuapp.com/notes
=end

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render json: @note, status: :created, location: @note }
        format.xml { render :xml => @note }
      else
        format.html { render action: "new" }
        format.xml { render :xml => "Failed"}
        flash[:notice] = "Failed to save."
      end
    end
  end

  # PUT /notes/1
  # PUT /notes/1.json
  def update
    @note = Note.find(params[:id])

    respond_to do |format|
      if @note.update_attributes(params[:note])
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note = Note.find(params[:id])
    @note.destroy

    respond_to do |format|
      format.html { redirect_to notes_url }
      format.json { head :no_content }
    end
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<h1>Listing courses</h1>

<table class="table table-striped">
  <tr>
    <th>Name</th>
    <th>Id</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @courses.each do |course| %>
  <tr>
    <td><%= course.name %></td>
    <td><%= course.id %></td>
    <td><%= link_to 'Show Notes', course, :class =>"btn btn-link" %></td>
    <td><%= link_to 'Edit Name', edit_course_path(course), :class =>"btn btn-link" %></td>
    <td><%= link_to 'Delete Course', course, method: :delete, data: { confirm: 'Are you sure?' }, :class =>"btn btn-link" %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Course', new_course_path, :class =>"btn btn-primary btn-large" %>

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path, :class =>"btn btn-link"  %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p></p>
<p>
  <b>Name:</b>
  <%= @course.name %>
</p>
          <br/>

<% if @course.notes.size > 0 %>
<div class="container-fluid">
  <%= render '/notes/note' %>
</div>
<% end %>

<br/>


<%= link_to 'Back', courses_path, :class =>"btn btn-link"  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body>
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Notility", '/static_pages/home.html', id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Courses",    '/courses' %></li>
          <li><%= link_to "Notes",    '/notes' %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>
<div class="container">
  <%= yield %>

  <footer class="footer">
    <small>
      Copyright 2012 Omkar Ambardekar
    </small>
    <nav>
      <small class="nav pull-right">Website created using help from <a href="http://railstutorial.org/">Rails Tutorial</a>
        by Michael Hartl</small>
    </nav>
  </footer>

</div>
</body>
</html>

app/views/notes/_form.html.erb
<div class="container">

  <%= form_for @note, :html => {:class => "form-horizontal"} do |f| %>
      <% if @note.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

            <ul>
              <% @note.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="field">
        <%= f.label :tag %><br />
        <%= f.text_field :tag %>
      </div>

      <div class="field">
        <%= f.label :course_id %>
        <%= f.collection_select :course_id, Course.all, :id, :name, :class => "dropdown-menu", :prompt => "Select a course" %>
      </div>

      <!--<div class="field">
        <%#= hidden_field_tag(:user_id, "1", :name => "note[hidden]") %>
      </div>-->

      <div class="field">
        <%= f.text_area :content, placeholder: "Write a new note..." %>
      </div>
      <%= f.submit "Post", class: "btn btn-large btn-primary" %>

  <% end %>
</div>

app/views/notes/_note.html.erb
<table class="table table-striped">
  <tr class="success">
    <th>Content</th>
    <th>Course</th>
    <th>Tag</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @notes.each do |note| %>
      <tr>
        <td><%= note.content %></td>
        <td><%= Course.find(note.course_id).name %></td>
        <td><%= note.tag %></td>
        <td><%= link_to 'Show', note %></td>
        <td><%= link_to 'Edit', edit_note_path(note) %></td>
        <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
</table>

app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note, :class =>"btn btn-link"  %> |
<%= link_to 'Back', notes_path, :class =>"btn btn-link"  %>

app/views/notes/get_note.html.erb
<%= render 'note' %>

app/views/notes/index.html.erb
<h1>Listing notes</h1>

<br/>

<%= form_tag notes_path, :method => 'get', :id => "notes_search", :class => "form-search" do %>

    <p>
      <%= text_field_tag :search, params[:search], :class =>"span2 search-query" %>
      <%= submit_tag "Search", :name => nil, :class => "btn" %>
    </p>
    <div id="notes"><%= render 'note' %></div>

<% end %>

<br/>

<%= link_to 'New Note', new_note_path, class: "btn btn-small btn-primary" %>

app/views/notes/index.js.erb
$("#notes").html("<%= escape_javascript(render("note")) %>");

app/views/notes/new.html.erb
<h1>New note</h1>

<%= render 'form' %>

<%= link_to 'Back', notes_path, :class =>"btn btn-link"  %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @note.content %>
</p>

<p>
  <b>Course:</b>
  <%= Course.find(@note.course_id).name %>
</p>

<p>
  <b>Tag:</b>
  <%= @note.tag %>
</p>

<%= link_to 'Edit', edit_note_path(@note), :class =>"btn btn-link" %> |
<%= link_to 'Back', notes_path, :class =>"btn btn-link"  %>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Welcome to Notility</h1>

  <h2>
    Easy way to share your lecture notes
  </h2>



</div>

<div class="center">
  <%= image_tag("Notes.png", alt: "Notes")%>
</div>

<div class="center">
  <%= link_to "Show Courses", courses_path, class: "btn btn-large btn-primary" %>
</div>


<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>